AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'spec/*.rb'

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false
